### ISSUE TITLE
Wrong 'matching element' is highlighted

### ISSUE THREAD

**Issue by dander** [atom/language-xml#17]
Atom version 0.136

The below sample text, when placing the cursor within the second 'Directory' element, the wrong matching element is shown. This doesn't seem to affect code folding. I also tried setting the language to "Property List (XML)" and the issue is there as well. I'm not sure if I should open another issue for that.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">

  <Fragment>
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder">
        <Directory Id="INSTALLFOLDER" Name="PatchFamilyTest" />
      </Directory>
    </Directory>
  </Fragment>

</Wix>
```

![image](https://cloud.githubusercontent.com/assets/1302979/4632905/10be4bb2-53c2-11e4-88ab-adab21f14255.png)

**Comment by 50Wliu** [comment]
This is *probably* due to bracket-matcher not recognizing `/>` as valid.

**Comment by dander** [comment]
Thanks. I agree this seems to be caused by that issue: atom/bracket-matcher#115. So I will close this one.
