### ISSUE TITLE
add new snippets 

### ISSUE THREAD

**Issue by StatelessCat** [atom/language-xml#22]
Hey,
I'm looking for a way to dynamicaly add new snippets to language-xml.cson, is it possible ? 
Because when i define some snippets for XML in ~/.atom/snippets.cson, they are not loaded.

Thanks

**Comment by lee-dohm** [comment]
Yes, you can add snippets for any language in `~/.atom/snippets.cson`. A couple things to keep in mind:

1. CSON is an indentation-sensitive language
1. CSON, like JSON, is an object notation. This means that if you use the same key multiple times, the last one wins and overwrites the older ones.

If you've double-checked these and you're still having trouble, feel free to post your `snippets.cson` here or in a Gist and we can perhaps help you debug.

**Comment by StatelessCat** [comment]
Thanks for your help, i found the reason of my issue, i was using 
```
'.source.xml':
```
instead of 
```
'.text.xml':
```
What is the reason for XML to be treated like "text" ?

**Comment by lee-dohm** [comment]
It's largely arbitrary and most likely came over from the initial conversion from the TextMate package. If you want a reason, markup languages are not "source" in that they are not "compiled" or "interpreted" into executable code in the traditional sense. Then again, the same can be said of Markdown, but its scope is `.source.gfm` ... so there you are ... arbitrary :grinning:

It sounds like this is resolved so I'm going to close it. Let us know if you have any more issues!

**Comment by StatelessCat** [comment]
Thanks for the explaination :)
