### ISSUE TITLE
Remove mxml from xml-lang

### ISSUE THREAD

**Issue by Nu77** [atom/language-xml#23]
@kevinsawicki MXML should be supported by:
https://atom.io/packages/language-flex

**Comment by kevinsawicki** [comment]
Keeping it here allows them to still be highlighted when `language-flex` is not installed.

Is having the `.mxml` extension here causing issues when using the `language-flex` package?

**Comment by Nu77** [comment]
atom/atom#6847 was fixed, seems no problem.
Thanks.
