### ISSUE TITLE
Issue with syntax coloring/leading spaces

### ISSUE THREAD

**Issue by pgkos** [atom/language-xml#28]
There is a small issue with syntax coloring which I have observed in XML files (I am not sure if it occurs with other syntaxes). I think the issue did not occur in previous versions of Atom.
![xml_coloring_bug](https://cloud.githubusercontent.com/assets/11692818/8103109/30118bac-1026-11e5-8e36-1e18279269da.png)
As you can see, the color spans are moved by one character forward on the lines which only contain an XML attribute. The issue occurs only if the number of leading spaces on these lines is even.
(Atom 0.207.0, Ubuntu 14.04 64-bit)

**Comment by izuzak** [comment]
@pgkos Strange, I'm not seeing that behavior on the latest master version of Atom:

![screen shot 2015-06-11 at 12 28 58](https://cloud.githubusercontent.com/assets/38924/8105041/cfa90a6e-1035-11e5-8d3f-1266410f033e.png)

Do you see the same problem in Atom 0.208.0 and in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

Also, can you take that screenshot again, but with the invisible characters turned on? Go to Settings and turn on "Show invisibles".

**Comment by pgkos** [comment]
I have taken this screenshot in safe mode, the issue still occurs:
![xml_coloring_bug_2](https://cloud.githubusercontent.com/assets/11692818/8105255/cdcf309a-1037-11e5-8085-0a4eceb134f8.png)
I can confirm that the same issue also occurs in Atom 0.206.0 on Ubuntu (different computer), but on Mac OS X 10.10 everything is fine.

**Comment by izuzak** [comment]
Thanks for checking. 

That's strange -- I was able to reproduce this in 0.206.0 on Ubuntu, but not on 0.208.0. Can you please confirm that you are running 0.208.0 (in your last message you mentioned that you tried 0.206.0)?

**Comment by pgkos** [comment]
Yes, I am running Atom 0.208.0.

I just did a complete purge/reinstall of Atom 0.208.0 on an Ubuntu computer and the XML issue doesn't occur anymore. (I also tried removing the `~/.atom` directory but it didn't solve the issue)

Out of curiosity, I did a `diff` of `/opt/atom` directories (one before and one after reinstall) and it seems that the following packages are not properly updated while installing/updating Atom on Ubuntu (I am installing/updating atom via Ubuntu ppa):
```
/opt/atom/resources/app/apm/node_modules/yargs/node_modules/cliui/node_modules/center-align/
/opt/atom/resources/app/apm/node_modules/yargs/node_modules/cliui/node_modules/right-align/
```

and also

```
/opt/atom/resources/app/apm/node_modules/first-mate/node_modules/grim/node_modules/coffeestack/node_modules/source-map/node_modules/amdefine/
/opt/atom/resources/app/apm/node_modules/first-mate/node_modules/oniguruma/
/opt/atom/resources/app/apm/node_modules/git-utils/
/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/
/opt/atom/resources/app/apm/node_modules/plist/package.json
```

so, this is probably an issue with ppa/apt.

**Comment by 50Wliu** [comment]
Glad to hear that reinstalling fixed your issue, @pgkos.  As for the PPA issue, you may want to report that to Webupd8.
