### ISSUE TITLE
Indent guide is crazy

### ISSUE THREAD

**Issue by Yajo** [atom/language-xml#42]
Indent guide lines become crazy all the time:

![captura de pantalla de 2015-12-31 10-55-16](https://cloud.githubusercontent.com/assets/973709/12063319/06513688-afad-11e5-8358-4b781dfea681.png)

Atom 1.3.2.

**Comment by lee-dohm** [comment]
The indent guide is a feature of the base editor. Please open this on the https://github.com/atom/atom repository. 

Also, could you give some more information when you do? Such as:

* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
