### ISSUE TITLE
Implement reasonable firstLineMatch pattern

### ISSUE THREAD

**Issue by LIyoai** [atom/language-xml#59]
XML files without a .xml file extension have no syntax highlighting

See: https://github.com/atom/atom/issues/12678

**Comment by Alhadis** [comment]
Quoting @thomasjo in atom/atom#12678:

> I propose you open a new issue on language-xml with a request that a reasonable `firstLineMatch` pattern be implemented that will detect XML (and XSL) files without extensions.

I believe this was adequately addressed in atom/language-xml#74, so it's safe to mark this resolved. =)
