### ISSUE TITLE
Support for SLD

### ISSUE THREAD

**Issue by prebm** [atom/language-xml#68]
Hi,

I am working a lot with [SLD](https://en.wikipedia.org/wiki/Styled_Layer_Descriptor) which is also an XML schema. Please add it to the list of supported file-types.

Additionally I wanted to ask if it would be possible to add file types on my own in the settings.

Cheers,
Benjamin

**Comment by 50Wliu** [comment]
Hey @prebm!  Adding a filetype to the list of recognized filetypes is extremely simple: just add it to [this list](https://github.com/atom/language-xml/blob/7886ae9817ea72b61eec5a3448065ecb36b05e30/grammars/xml.cson#L3) while keeping it in order and send a PR.

See [this FAQ](https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539) for how you can change filetype assocations manually.

**Comment by StevenTang166** [comment]
I think this issue can be closed now.
