### ISSUE TITLE
Code folds incorrectly with multiline CDATA sections

### ISSUE THREAD

**Issue by alexchandel** [atom/language-xml#79]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Attempting to fold code sections breaks when the XML file contains multiline CDATA sections. Folding doesn't progress past the line containing the beginning of the `CDATA` section.

### Steps to Reproduce

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<outer>
    <inner test=".test[test].0">
        <![CDATA[a'ed foo
foo test
test bar
biz]]>
    </inner>
</outer>
```

1. Open a file containing the XML above.
2. Attempt to fold at the 3rd line (the opening `inner` tag).

**Expected behavior:** The entire `inner` tag should fold, 6 lines into 1 line.

**Actual behavior:** Only 2 lines fold, and the `foo test` line & after remains.

**Reproduces how often:** Always

Try the same thing for the `outer` tag, and the folding ends at the `CDATA` line.

### Versions

macOS 10.12.5
```
atom --version
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by 50Wliu** [comment]
Looks like you found atom/atom#3442.
