### ISSUE TITLE
Highlighting fails for large XML files

### ISSUE THREAD

**Issue by alexchandel** [atom/language-xml#80]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Large, legal XML files fail to highlight with this grammar. In particular a 3.9 MB file, with roughly 30,000 nodes, doesn't highlight at all.

Moreover, even if I delete the entire contents of the file except for the outermost tag pairs, while keeping the tab open, the grammar never highlights it. Switching the tab to another grammar and then switching it back to XML doesn't fix it either. The tab has to be closed and reopened.

### Steps to Reproduce

1. Open a large, legal XML file (smallest replication case had 30571 lines, 2.0MB) that contains nested tags with attributes and CDATA sections.
2. It doesn't highlight
3. Delete everything except the outermost tag pairs, yielding a ≈3 line XML file.
4. It still doesn't highlight.
5. Change grammar to `C`, and then back to `XML`.
6. It still doesn't highlight

**Expected behavior:** Syntax highlighting should've occurred 

**Actual behavior:** the text remains unhighlighted

**Reproduces how often:** If the file is large enough (or complex enough, or whatever the condition is) to cause it, then always.

### Versions

macos 10.12.5

```
atom --version
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by Gatts1912** [comment]
For me, XML syntax highlighting works until the file size goes over 2048 KB. Anything larger is a no-go. This is the only reason I do not use Atom as I regularly work with XML structures well over this size; 15+ MB.

**Comment by chrisvio** [comment]
I am also experiencing this issue. XML file with > 53,000 lines will not highlight. The file is 2,297 KB. Atom v1.19. Thought I'd give it a try with the rendering re-write. Looks like It's back to Sublime!

**Comment by baileysh** [comment]
I have run into this as well.. anyone looking into this ?

**Comment by chrisvio** [comment]
I'm running into this with JSON files as well. Seems to be an Atom limitation rather than this particular language package.

**Comment by chrisvio** [comment]
Looks like we are out of luck. Apparently this is a built-in "feature". From https://github.com/atom/atom/issues/11232 -
> The following behavior is expected:
> Files larger than 2MB will not be syntax highlighted - #7130

This is like a car manufacturer preventing their car from going over 30 MPH per hour because if driven too fast it uses too much gas. Lame "solution".

They should at least make the size limit user configurable or even give users the option to disable it altogether. To force this limitation on users stinks. It's lousy UX design.

**Comment by alexchandel** [comment]
The 2MB limit is annoying/a bug, but that's only half of this issue. The other half is that large tabs, once reduced below the 2 MB limit, still fail to highlight. In my example, a 2 MB file is cut to < 1kB, and it still fails to highlight.

**Comment by twifty** [comment]
Why has this been closed? In todays day and age a 2MB XML file is considered small. As @chrisvio said above, it should at least be made configurable.

**Comment by dennorske** [comment]
I am also looking for a way to tweak atom, so you can force-highlight the lengthier files on purpose.
This was disabled due to performance improvements. There is no information from the editor itself to be seen when the restriction takes place, no message or anything. @twifty 
How come sublime and other text editors have 0 issues regarding this? even performance wise, they are great.

**Comment by izzybe** [comment]
I know - this issue shows closed. The issue still exists for large XML files. For some reason - my work around works, I cut a section out of XML - do a save with a smaller file size - reopen that particular file (it will show syntax highlights) and paste the other section back in and the syntax highlights still work.

**Comment by jawanns** [comment]
Definitely still an issue with very large XML files. I'm currently working with a 165 MB file that's close to 4 million lines. Syntax highlighting doesn't work AND only the first 1,398,101 lines are displayed.
