### ISSUE TITLE
Highlighting for malformed comment looks like well-formed comment

### ISSUE THREAD

**Issue by PeteDevoy** [atom/language-xml#84]
### Prerequisites

*  [x] Put an X between the brackets on this line [...]

### Description

[XML grammar forbids](https://www.w3.org/TR/xml/#sec-comments) comment ending in triple dash `--->` but this grammar appears to accept it.  This can make troubleshooting XML parse errors quite confusing because parts of the document are parsed as commented out even though the XML looks well-formed to the eye.

### Steps to Reproduce

```
<?xml version="1.0" encoding="utf-8"?>
<foo>Bar
<!--malformed comment--->
Baz
</foo>
```

1. Create XML file as above
2. View in Atom with safe mode

**Expected behavior:**
Something like vim:
![image](https://user-images.githubusercontent.com/4375326/36947226-002b1586-1fc1-11e8-81aa-c07f9bae364b.png)

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/4375326/36947259-57e13c6a-1fc1-11e8-9b59-e6ce54bd8036.png)

**Reproduces how often:**
100%

## Atom
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

## apm
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.7.4

## OS
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by TangSteven** [comment]
@50Wliu This issue can be closed now I think.
