### ISSUE TITLE
Tag matching issue

### ISSUE THREAD

**Issue by surdu** [atom/language-xml#85]
<img width="348" alt="screen shot 2018-04-26 at 12 00 44" src="https://user-images.githubusercontent.com/11520795/39296706-4cd519ce-494a-11e8-9ab8-84f79b82190c.png">

As you can see, the closing tag was missmatched. It should have underlined the last tag, not the one it did.

I know this in not common tag-ing for XML but working with NativeScript it's quite common.

The files uses the XML grammar.

Versions:
Atom: 1.27.0-beta0
xml-language: 0.35.2

**Comment by TangSteven** [comment]
Reproduced in 1.28.0, also occurs when language is set to HTML.
I don't think that this is not a problem with the language-xml package, but with [atom/bracket-matcher](https://github.com/atom/bracket-matcher) I suggest filling the issue in that repository.

**Comment by surdu** [comment]
Ah, now that make so much sense. I was wondering why I can't find any tag matching code in this repo 😅
