### ISSUE TITLE
XML syntax definition problem

### ISSUE THREAD

**Issue by alexr00** [atom/language-xml#96]
_From @omochi on January 19, 2019 17:0_

I may found bug of syntax.

https://github.com/Microsoft/vscode/blob/10a1d2a50a2882f5ae85bdb51eb04d3064fb9de9/extensions/xml/syntaxes/xml.tmLanguage.json#L354-L363

It should be:

```
 { 
 	"begin": "<%--", 
 	"captures": { 
 		"0": { 
 			"name": "punctuation.definition.comment.xml" 
 		}
	}, 
 	"end": "--%>", 
 	"name": "comment.block.xml"  
 }, 
```

_Copied from original issue: Microsoft/vscode#66776_

**Comment by alexr00** [comment]
_From @omochi on January 19, 2019 17:24_

Oh, I found more.

https://github.com/Microsoft/vscode/blob/10a1d2a50a2882f5ae85bdb51eb04d3064fb9de9/extensions/xml/syntaxes/xml.tmLanguage.json#L375-L380

should be:

```
"match": "--(?!>)",
"captures": {
    "0": {
        "name": "invalid.illegal.bad-comments-or-CDATA.xml"
    }
}
```

**Comment by omochi** [comment]
I recorded video.

https://www.youtube.com/watch?v=UeCwolx7oW0&feature=youtu.be

First issue: 
`begin` and `end` are not paired.
So `punctuation.definition.comment.xml` scope does not constructed.

Second issue:
`invalid.illegal.bad-comments-or-CDATA.xml` is single token and not scope.
So `match` rule is better than `begin`.

VSCode process `begin` without `end` as `match`.
So no user level issue is. It is just for technically quality.
Because textmate syntax file is kinda interchangeable among some text editors.

**Comment by rsese** [comment]
Thanks @omochi -

> First issue:
> `begin` and `end` are not paired.
> So `punctuation.definition.comment.xml` scope does not constructed.

It looks like your example is:

```xml
<%-- --%>
```

I think those are JSP comments, not XML comments?  In Atom, if I set the language to JSP the closing `--%>` is recognized correctly:

![jsp-comment](https://github-slack.s3.amazonaws.com/monosnap/test.jsp__worktest-tree-sitter_2019-01-25_13-40-46.png)

x-ref: https://github.com/atom/language-xml/pull/87 and https://github.com/atom/language-xml/commit/0a04e02d4b179688526938f19ae3de666fe07770

Let me know if I'm misunderstanding something here.

> Second issue:
> `invalid.illegal.bad-comments-or-CDATA.xml` is single token and not scope.
> So `match` rule is better than `begin`.

Your example here is:

```xml
<!-- -- -->
```

Related to the PR above, I believe this is already reported here: https://github.com/atom/language-xml/issues/91

**Comment by omochi** [comment]
More information about report (2).

I reported same concept for PHP syntax.

https://github.com/Microsoft/vscode/issues/66809

They accept it and make PR to patch this.

https://github.com/atom/language-php/pull/352

This PR is also reviewed by @rsese . I say same things.
