### ISSUE TITLE
Highlight CSS inside style tags and attributes (for example in SVGs)

### ISSUE THREAD

**Issue by ariasuni** [atom/language-xml#97]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

SVG files are XML files that can contain CSS, but this package doesn’t highlight CSS in those files.

### Steps to Reproduce

1. Download the Breeze [Mail forwarded replied](https://github.com/KDE/breeze-icons/blob/master/icons/actions/16/mail-forwarded-replied.svg?short_path=d709b82).
2. Open it in Atom.

**Expected behavior:**

Line 4 to 6, and text in the `style` attribute at line 9 are highlighted as CSS.

(this is an edited image)

![screenshot_20190128_203653_montage](https://user-images.githubusercontent.com/2446451/51862363-c0bbfa00-233e-11e9-818b-4d43a4617252.png)

**Actual behavior:**

Line 4 to 6 are not highlighted, and text in the `style` attribute at line 9 is highlighted like any other string.

![screenshot_20190128_202856](https://user-images.githubusercontent.com/2446451/51861553-d9c3ab80-233c-11e9-92ea-fcece94a7c25.png)

**Reproduces how often:** Everytime

### Versions

Arch Linux

```
Atom    : 1.34.0
Electron: 3.1.1
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

**Comment by rsese** [comment]
Thanks for the suggestion!  I talked to the other maintainers about this and while we think this could be useful for people working with .svg files, it's not something the team would take on and could also be implemented as a general SVG language community package (e.g. https://atom.io/packages/language-svg seems to highlight the embedded CSS?).  Since it's not something the team would prioritize, we're going to close the issue but thanks again for the idea.

**Comment by ariasuni** [comment]
That package doesn’t work as expected either so [I opened an issue there](https://github.com/erikdahlstrom/language-svg/issues/6).
